POST http://localhost:3000/api/tags
Content-Type: application/json

{
  "user": "666ab8a2592ccb79541c8158",
  "columnId": 30833,
  "cardId": 7940,
  "text": "웃기시네",
  "color": "#76a5ea"
}

###

DELETE http://localhost:3000/api/tags/666ab8dc592ccb79541c815a

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "userId": 3643
}

###

GET http://localhost:3000/api/tags/666aaa9662d3c425ad993392

###

GET http://localhost:3000/api/tags
